<% require 'date' %>
---
driver:
  name: ec2
  shared_credentials_profile: 'test-kitchen'
  region: us-west-2
  availability_zone: b
  skip_cost_warning: true #Skip the warnring that this may cost money
  spot_price: 0.06
  instance_type: t2.large
  subnet_id: ENV['subnet']
  tags:
    Name: 'test-kitchen'
    Environment: 'test'
    created-by: 'test-kitchen'
    created-at: <%= DateTime.now.strftime("%Y/%m/%d %H:%M") %>
    running-on: <%= Socket.gethostname %>
provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.11
  always_update_cookbooks: true
  client_rb:
    log_level: 'warn'
verifier:
  name: inspec

platforms:
  - name: windows-2016
    attributes:
      if_name: 'Ethernet'
  - name: windows-2012r2
    attributes:
      if_name: 'Ethernet 2'
transport:
  name: winrm
  elevated: true
 

suites:
  - name: default
    run_list:
      - recipe[test::default]
