name 'windows_route'
maintainer 'Mendy Baitelman'
maintainer_email 'mendy@baitelman.com'
license          'Apache-2.0'
description 'Installs/Configures windows_route'
long_description 'Installs/Configures windows_route'
version '0.1.0'
chef_version '>= 13.0'
supports         'windows'

issues_url 'https://github.com/mbaitelman/windows_route/issues'
source_url 'https://github.com/mbaitelman/windows_route'
